### ISSUE TITLE
Emacs server as an alternative?

### ISSUE THREAD

**Issue by xuchunyang** [twlz0ne/with-emacs.el#2]
I just learnt a new function `server-eval-at` from [(emacs) Emacs Server](https://www.gnu.org/software/emacs/manual/html_node/emacs/Emacs-Server.html),

```el
(shell-command "/Users/xcy/bin/emacs-24.4 -Q --daemon=foo")
;; => 0

(server-eval-at "foo" 'emacs-version)
;; => "24.4.1"

(server-eval-at "foo" '(kill-emacs))
;; => nil
```

**Comment by twlz0ne** [comment]
@xuchunyang Thanks for your idea.
I implemented a preliminary version at https://github.com/twlz0ne/with-emacs.el/commit/ef5b0175fed465fd13430ac4584ecc42e6683d1d :

```elisp
;; Evaluate exprs on server "foo" or signal an error if no such server. 
(with-emacs-server "foo" ...)

;; Evaluate exprs on server "foo" and start a server if necessary. 
(with-emacs-server "foo" :ensure t ...)
(with-emacs-server "foo" :ensure "/path/to/emacs" ...)
```


Do you have any suggestions?

**Comment by xuchunyang** [comment]
Looks good. I've tried it. Feel free to close this issue.
